=== HediAbed/codecharta/visualization/app/codeCharta/util/generatedSchema.json
{
	"$ref": "#/definitions/ExportCCFile",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"AttributeType": {
			"additionalProperties": {
				"enum": ["absolute", "relative"],
				"type": "string"
			},
			"type": "object"
		},
		"AttributeTypes": {
			"additionalProperties": false,
			"properties": {
				"edges": {
					"items": {
						"$ref": "#/definitions/AttributeType"
					},
					"type": "array"
				},
				"nodes": {
					"items": {
						"$ref": "#/definitions/AttributeType"
					},
					"type": "array"
				}
			},
			"type": "object"
		},
		"CodeMapNode": {
			"additionalProperties": false,
			"properties": {
				"attributes": {
					"$ref": "#/definitions/KeyValuePair"
				},
				"children": {
					"items": {
						"$ref": "#/definitions/CodeMapNode"
					},
					"type": "array"
				},
				"deltas": {
					"additionalProperties": {
						"type": "number"
					},
					"type": "object"
				},
				"edgeAttributes": {
					"additionalProperties": {
						"$ref": "#/definitions/EdgeMetricCount"
					},
					"type": "object"
				},
				"link": {
					"type": "string"
				},
				"name": {
					"type": "string"
				},
				"path": {
					"type": "string"
				},
				"type": {
					"type": "string"
				},
				"visible": {
					"type": "boolean"
				}
			},
			"required": ["name", "type"],
			"type": "object"
		},
		"Edge": {
			"additionalProperties": false,
			"properties": {
				"attributes": {
					"$ref": "#/definitions/KeyValuePair"
				},
				"fromNodeName": {
					"type": "string"
				},
				"toNodeName": {
					"type": "string"
				},
				"visible": {
					"$ref": "#/definitions/EdgeVisibility"
				}
			},
			"required": ["attributes", "fromNodeName", "toNodeName"],
			"type": "object"
		},
		"EdgeMetricCount": {
			"additionalProperties": false,
			"properties": {
				"incoming": {
					"type": "number"
				},
				"outgoing": {
					"type": "number"
				}
			},
			"required": ["incoming", "outgoing"],
			"type": "object"
		},
		"EdgeVisibility": {
			"enum": ["both", "from", "none", "to"],
			"type": "string"
		},
		"ExportBlacklistItem": {
			"additionalProperties": false,
			"properties": {
				"path": {
					"type": "string"
				},
				"type": {
					"$ref": "#/definitions/ExportBlacklistType"
				}
			},
			"required": ["path", "type"],
			"type": "object"
		},
		"ExportBlacklistType": {
			"enum": ["exclude", "hide"],
			"type": "string"
		},
		"ExportCCFile": {
			"additionalProperties": false,
			"properties": {
				"apiVersion": {
					"type": "string"
				},
				"attributeTypes": {
					"$ref": "#/definitions/AttributeTypes"
				},
				"blacklist": {
					"items": {
						"$ref": "#/definitions/ExportBlacklistItem"
					},
					"type": "array"
				},
				"edges": {
					"items": {
						"$ref": "#/definitions/Edge"
					},
					"type": "array"
				},
				"markedPackages": {
					"items": {
						"$ref": "#/definitions/MarkedPackage"
					},
					"type": "array"
				},
				"nodes": {
					"items": {
						"$ref": "#/definitions/CodeMapNode"
					},
					"type": "array"
				},
				"projectName": {
					"type": "string"
				}
			},
			"required": ["apiVersion", "nodes", "projectName"],
			"type": "object"
		},
		"KeyValuePair": {
			"additionalProperties": {
				"type": "number"
			},
			"type": "object"
		},
		"MarkedPackage": {
			"additionalProperties": false,
			"properties": {
				"attributes": {
					"additionalProperties": {},
					"type": "object"
				},
				"color": {
					"type": "string"
				},
				"path": {
					"type": "string"
				}
			},
			"required": ["attributes", "color", "path"],
			"type": "object"
		}
	}
}

=== HediAbed/codecharta/analysis/import/SourceCodeParser/src/test/resources/jsonMetricValues.json
{
  "nodes": [
    {
      "children": [
        {
          "children": [
            {
              "children": [],
              "name": "foo.java",
              "link": "",
              "attributes": {
                "rloc": 3,
                "mcc": 2
              },
              "type": "File"
            }
          ],
          "name": "foo.java",
          "link": "",
          "attributes": {},
          "type": "Folder"
        },
        {
          "children": [
            {
              "children": [],
              "name": "bar.kt",
              "link": "",
              "attributes": {
                "rloc": 4,
                "mcc": 1
              },
              "type": "File"
            }
          ],
          "name": "bar.kt",
          "link": "",
          "attributes": {},
          "type": "Folder"
        }
      ],
      "name": "root",
      "link": "",
      "attributes": {},
      "type": "Folder"
    }
  ],
  "apiVersion": "1.1",
  "attributeTypes": {},
  "edges": [],
  "blacklist": [],
  "projectName": "foo"
}
